name: Vulnerability scans

permissions: read-all

# description: |
#   A fast vulnerability scan on the repo that effectively supplements ossf scorecard and codesql
#   and may run every day.
#
#   Trivy reports are often more easily actionable than codeql reports.
#
# TODO(fredbi): we may supplement this analysis with snyk (to be experimented with) (requires a token).

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '18 4 * * *'

jobs:
  analysis:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      -
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      -
        name: Vulnerability scan by trivy
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          scan-type: repo
          format: sarif
          hide-progress: false
          output: trivy-code-report.sarif
          scanners: vuln,secret
          exit-code: 0
      -
        name: Upload trivy findings to code scanning dashboard
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4.30.9
        with:
          category: trivy
          sarif_file: trivy-code-report.sarif
